### ISSUE TITLE
LibGDX addIcon file not found

### ISSUE THREAD

**Issue by mertl-tgm** [mertl-tgm/ITP-Projekt#3]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: icon_32.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:148)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:189)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:142)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: icon_32.png (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:145)
	... 3 more

**Comment by mertl-tgm** [comment]
assets Folder must be a source folder
